
## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  data:
    mongodb:
      uri: mongodb://localhost:27017/transito
  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  freemarker:
    suffix: .ftlh


server:
  port: 8081

file:
  upload-dir: /files/

springbootwebfluxjjwt:
  password:
    enconder:
      secret: mysecret
      iteration: 33
      keylength: 256

  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    expiration: 28800

amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIA465J23FPST6J5C4D
  secretKey: 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
  bucketName: files-transito

dropbox:
  accessToken: sl.BM1zGtSKu61GIpVHoeSlcZkhuynBymREQyFHizqHS_g36YC7a3VdfHJHMLhFVnFA_4_MBbeasimuZP-zZtMLt7bhX9S_dOCz4GtGZqQ5RgtCALBPg9MzeNWOjD0U21rThtbB-20n